#!/bin/bash


_get_repolink () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $PMPERMIT_REPO == "PmPermit" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1Jbm5leGlhL1BtU2VjdXJpdHkvYXJjaGl2ZS9tYXN0ZXIuemlw=" | base64 -d
    elif [[ $PMPERMIT_REPO == "PMPERMIT" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1Jbm5leGlhL1BtU2VjdXJpdHkvYXJjaGl2ZS9tYXN0ZXIuemlw=" | base64 -d
    elif [[ $PMPERMIT_REPO =~ $regex ]]
    then
        if [[ $PMPERMIT_REPO_BRANCH ]]
        then
            echo "${PMPERMIT_REPO}/archive/${PMPERMIT_REPO_BRANCH}.zip"
        else
            echo "${PMPERMIT_REPO}/archive/master.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1RlYW1Jbm5leGlhL1BtU2VjdXJpdHkvYXJjaGl2ZS9tYXN0ZXIuemlw=" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="pmpermit.zip"
    echo "  Downloading source code ..."
    wget -q $(_get_repolink) -O "$zippath"
    echo "  Unpacking Data ..."
    PMPERMITPATH=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    echo "  Cleaning ..."
    rm -rf "$zippath"
    sleep 5
    cd $USERPATH
    echo "    Starting Userbot    "
    echo "
STARTING PM PERMIT BOT
"

    python3 ./setup/updater.py ./requirements.txt requirements.txt
    python3 -m userbot
}

_set_bot
